name: translation_gen
description: Use AI to generate arb/json file with translations for your app l10n.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  chat_gpt_sdk: ^2.2.5
  drift: ^2.14.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  path: ^1.9.0
  riverpod: ^2.4.9

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  drift_dev: ^2.14.0
  build_runner: ^2.4.7
  flutter_lints: ^2.0.3

